apiVersion: v1
kind: ReplicationController
metadata:
  name: springapprc
spec:
  replicas: 2
  selector:
    app: springbootapp
  template:
    metadata:
      name: springbootapppod
      labels:
        app: springbootapp
    spec:
      containers:
        - name: springbootcontainer
          image: spring-boot-mongo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springappservice
spec:
  type: NodePort
  selector:
    app: springbootapp
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongorc
spec:
  replicas: 1
  selector:
    app: mongodb
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodbcontainer
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
